#!/usr/bin/python
import roslib
roslib.load_manifest('blast_interface')
import rospy
import BaseHTTPServer

class RequestHandler(BaseHTTPServer.BaseHTTPRequestHandler):
   def __init__(self, request, client_address, server):
      BaseHTTPServer.BaseHTTPRequestHandler.__init__(self, request, client_address, server)

   def do_GET(self):
      if (self.path == ""):
         self.path = "files/app.html"
      if (self.path[0:len("files/")] == "files/"):
         self.protocol_version='HTTP/1.1'
         self.send_response(200, 'OK')
         self.send_header('Content-type', 'html') #TODO for images
         self.end_headers()
         self.wfile.write(bytes("<html><head><title>Hello World </title></head><body>Hello World</body></html>"))


if (__name__ == "__main__"):
   rospy.init_node("grandslam_test")

   server = BaseHTTPServer.HTTPServer(("c1", 8080), RequestHandler)

   while not rospy.is_shutdown():
      server.handle_request()
      
