#!/usr/bin/env python

import roslib
roslib.load_manifest('door_blast')
import rospy
import math
import tf
from sensor_msgs.msg import *
from visualization_msgs.msg import *
from geometry_msgs.msg import *
from pr2_msgs.srv import *
from grandslam.msg import *
from kinematics_msgs.srv import *
from pr2_controllers_msgs.msg import *
from pr2_common_action_msgs.msg import *
from trajectory_msgs.msg import *
import actionlib

class DoorBlast:
    def __init__(self):
        self.scan_msg = None
        self.visualization_publisher = rospy.Publisher("/visualization_markers", Marker)
        self.cmd_vel_publisher = rospy.Publisher("/base_controller/command", Twist)
        self.listener = tf.TransformListener()
        rospy.loginfo("Wait for laser control")
        rospy.wait_for_service("/laser_tilt_controller/set_periodic_cmd")
        self.set_laser = rospy.ServiceProxy("/laser_tilt_controller/set_periodic_cmd", SetPeriodicCmd)
        rospy.Subscriber("/tilt_scan", LaserScan, self.on_scan_msg)
        self.blast_server = actionlib.SimpleActionServer("door_blast", GrandSlamTransitionAction, execute_cb=self.blast, auto_start=False)
        self.drag_server = actionlib.SimpleActionServer("door_drag", GrandSlamTransitionAction, execute_cb=self.drag, auto_start=False)
        rospy.loginfo("wait for IK")
        rospy.wait_for_service("pr2_right_arm_kinematics/get_ik_solver_info")
        rospy.wait_for_service("pr2_right_arm_kinematics/get_ik")
        self.query_client = rospy.ServiceProxy("pr2_right_arm_kinematics/get_ik_solver_info", GetKinematicSolverInfo)
        self.ik_client = rospy.ServiceProxy("pr2_right_arm_kinematics/get_ik", GetPositionIK)
        self.arm = rospy.Publisher("r_arm_controller/command", JointTrajectory)
        self.gripper = actionlib.SimpleActionClient("r_gripper_controller/gripper_action", Pr2GripperCommandAction)
        rospy.loginfo("Wait for tuck arm")
        self.tuck = actionlib.SimpleActionClient("tuck_arms", TuckArmsAction)
        self.tuck.wait_for_server()
        rospy.loginfo("Wait for torso")
        self.torso = actionlib.SimpleActionClient("/torso_controller/position_joint_action", SingleJointPositionAction)
        self.torso.wait_for_server()
        rospy.loginfo("started")
        self.blast_server.start()
        self.drag_server.start()


    def set_torso(self, pos, wait):
        traj = SingleJointPositionGoal()
        traj.position = pos
        traj.min_duration = rospy.Duration(1.0)
        traj.max_velocity = 0
        self.torso.send_goal(traj)
        if (wait):
            self.torso.wait_for_result()
    
    def on_scan_msg(self, msg):
        self.scan_msg = msg

    def wait_for_scan(self, clear = True):
        if (clear):
            self.scan_msg = False
        while not rospy.is_shutdown() and not self.scan_msg:
            rospy.sleep(0.01)

    def set_laser_pos(self, pos):
        laser_per = SetPeriodicCmdRequest()
        laser_per.command.header.stamp = rospy.Time.now()
        laser_per.command.profile = "linear"
        laser_per.command.period = 1
        laser_per.command.amplitude = 0
        laser_per.command.offset = pos
        resp1 = self.set_laser(laser_per)

    def set_laser_and_wait(self, pos):
        self.set_laser_pos(pos)
        rospy.sleep(2.0)
        self.wait_for_scan()


    def get_scan_point(self, x, y, z_goal):
        self.delete_markers(self.scan_msg.header.frame_id, 3)

        self.listener.waitForTransform(self.scan_msg.header.frame_id, "/base_footprint", rospy.Time(), rospy.Duration(30))
        tf = PointStamped()
        tf.header.frame_id = self.scan_msg.header.frame_id
        tf.point.x = x
        tf.point.y = y
        tf.point.z = 0
        print "Transform point"
        print tf


        marker = Marker()
        marker.header.frame_id = self.scan_msg.header.frame_id
        marker.header.stamp = rospy.get_rostime()
        marker.ns = "door_blast"
        marker.type = Marker.CUBE
        marker.action = Marker.MODIFY
        marker.id = 0
        marker.pose.position.x = x
        marker.pose.position.y = y
        marker.pose.position.z = 0
        marker.pose.orientation.x = 0.0
        marker.pose.orientation.y = 0.0
        marker.pose.orientation.z = 0.0
        marker.pose.orientation.w = 1.0
        marker.scale.x = 1.0
        marker.scale.y = 1.0
        marker.scale.z = 1
        marker.color.a = 1.0
        marker.color.r = 0.0
        marker.color.g = 0.0
        marker.color.b = 1.0
        self.visualization_publisher.publish(marker)
        
        pt_target = self.listener.transformPoint("/base_footprint", tf)
        
        pt_target.point.z = z_goal
        
        pos = 0.5
        
        while not rospy.is_shutdown():
            self.set_laser_pos(pos)
            rospy.sleep(1.0)
            self.listener.waitForTransform(self.scan_msg.header.frame_id, "/base_footprint", rospy.Time(), rospy.Duration(30))
            test = self.listener.transformPoint(self.scan_msg.header.frame_id, pt_target)
            print pos, test.point.z
            if (test.point.z < -0.3):
                pos = pos + 0.2
            elif (test.point.z > 0.3):
                pos = pos - 0.2
            elif (test.point.z < -0.05):
                pos = pos + 0.06
            elif (test.point.z > 0.05):
                pos = pos - 0.06
            elif (test.point.z < -0.01):
                pos = pos + 0.01
            elif (test.point.z > 0.01):
                pos = pos - 0.01
            else:
                break


    def blast(self, msg):
        self.set_torso(0.2, True)
        #Move to the right position away from the wall
        self.set_laser_and_wait(-0.3)
        min_depth = 0.0
        while min_depth < 1.5:
            self.wait_for_scan()
            min_depth = self.get_vertical_depth(self.scan_msg)
            print min_depth
            msg = Twist()
            msg.linear.x = -0.2
            print msg
            self.cmd_vel_publisher.publish(msg)
        self.cmd_vel_publisher.publish(Twist())
            
            
        #Line up straight along the wall
        print "Depth", min_depth
        self.get_scan_point(min_depth, 0, 0.3)
        angle = None
        while True:
            self.wait_for_scan()
            angle = self.line_up(self.scan_msg)
            if (angle):
                break

        #Side to side
        self.set_laser_and_wait(-0.3)
        hits = 0
        while True:
            self.wait_for_scan()
            if (self.horizontal_align(self.scan_msg, min_depth)):
                hits = hits + 1
                if (hits > 10):
                    break
            else:
                hits = 0

        #Go forward into the door
        goal = self.generate_goal(min_depth + 1.5, 0.0)
        self.move_to_target(goal, math.pi + math.pi/12.0)

        self.blast_server.set_succeeded(GrandSlamTransitionResult())

    def hand_dist(self, pos1):
        dist = 0.0
        for axis in zip(pos1, self.get_end_effector_pos()):
            delta = axis[0] - axis[1]
            dist = dist + (delta * delta)
        dist = math.sqrt(dist)
        return dist
    
    def mec_line_up(self, x, y):
        for i in range(0, 10):
            move = Twist()
            move.linear.x = x
            move.linear.y = y
            move.angular.z = -0.5
            self.cmd_vel_publisher.publish(move)
            rospy.sleep(0.1)
        for i in range(0, 10):
            move = Twist()
            move.linear.x = x
            move.linear.y = y
            move.angular.z = 0.5
            self.cmd_vel_publisher.publish(move)
            rospy.sleep(0.1)
        for i in range(0, 3):
            move = Twist()
            move.linear.x = x
            move.linear.y = y
            move.angular.z = -0.5
            self.cmd_vel_publisher.publish(move)
            rospy.sleep(0.1)
        
    def drag(self, msg):
        self.set_torso(0.2, True)
        #Move to the right position away from the wall
        self.set_laser_and_wait(-0.3)
        min_depth = 0.0
        hits = 0
        while not rospy.is_shutdown() and hits < 20:
            self.wait_for_scan()
            min_depth = self.get_vertical_depth(self.scan_msg)
            print min_depth
            msg = Twist()
            if (min_depth < 1.5):
                msg.linear.x = -0.2
                hits = 0
            elif (min_depth > 1.6):
                msg.linear.x = 0.2
                hits = 0
            else:
                hits = hits + 1
            print msg
            self.cmd_vel_publisher.publish(msg)
        self.cmd_vel_publisher.publish(Twist())

        #Line up straight along the wall
        print "Depth", min_depth
        self.get_scan_point(min_depth, 0, 0.3)
        angle = None
        while True:
            self.wait_for_scan()
            angle = self.line_up(self.scan_msg)
            if (angle):
                break

        goal = self.generate_goal(0, 0.2, True)
        self.move_to_target(goal, 0)

        #Line up side to side
        self.set_laser_and_wait(-0.3)
        hits = 0
        while True:
            self.wait_for_scan()
            if (self.horizontal_align(self.scan_msg, min_depth, 0.0)):
                hits = hits + 1
                if (hits > 10):
                    break
            else:
                hits = 0
    
        xpos = 0.2
        ypos = -0.5
        zpos = 1.1 + 0.2
        
        self.arm_move(xpos - 0.1, -0.7, zpos, 4.0)

        #Move up to the door
        goal = self.generate_goal(min_depth - 0.4, 0.8, True)
        self.move_to_target(goal, 0)

        door_center_goal = self.generate_goal(0.05 - 0.9, math.pi / 2)

        self.set_gripper(0.0)
        rospy.sleep(1.0)

        move = Twist()
        move.linear.x = 0.2
        move.linear.y = 0.0
        for i in range(0, 10):
            self.cmd_vel_publisher.publish(move)
            rospy.sleep(0.1)

        self.mec_line_up(0.1, 0.0)

        self.move_to_target(self.generate_goal(-0.2, 0), 0, True, True)

        self.arm_move(xpos, ypos, zpos, 2.0)
        while (xpos < 0.5 and not rospy.is_shutdown()):
            self.arm_move(xpos, ypos, zpos, 0.3)
            if (self.hand_dist((xpos, ypos, zpos)) > 0.01):
                break
            xpos = xpos + 0.01
        xpos = xpos - 0.04

        ypos = -0.5
        self.arm_move(xpos, ypos, zpos, 1.0)
        while (ypos < 0.0 and not rospy.is_shutdown()):
            self.arm_move(xpos, ypos, zpos, 0.3)
            if (self.hand_dist((xpos, ypos, zpos)) > 0.01):
                break
            ypos = ypos + 0.01
        
        if (ypos >= 0):
            self.tuck_arms()
            #self.move_to_target(self.generate_goal(-0.9, math.pi / 2))
            self.drag(msg)

        target_pos = self.get_end_effector_pos()
        self.arm_move(xpos - 0.1, target_pos[1] - 0.20, zpos, 3.0)
        self.arm_move(xpos - 0.1, target_pos[1] + 0.03, zpos, 3.0)

        self.set_gripper(0.086)

        rospy.sleep(1.0)

        print target_pos
        self.arm_move(xpos + 0.1, target_pos[1] + 0.03, zpos)

        rospy.sleep(1.0)
        
        self.set_gripper(0.00)

        
        target_pos = self.get_end_effector_pos()
        self.arm_move(xpos, -0.46, zpos, 5.0, False) 
        goal = self.generate_goal(0.46 + target_pos[1], math.pi / 2)
        self.move_to_target(goal, 0.0)
        rospy.sleep(5.0)

        #Cancel out forward and backwards offset
        self.move_to_target(self.generate_goal(xpos - target_pos[0], 0), 0)

        #Turn to face the door
        self.move_to_target(self.generate_goal(0.05, -math.pi / 2), -math.pi / 2, True, True)
        self.move_to_target(self.generate_goal(0.05, 0.0), -math.pi / 4, True, True)
        self.move_to_target(self.generate_goal(0.05, math.pi / 4), -math.pi / 7, True, True, time_limit=5.00)
        
        for step in range(0, 20):
            cmd = Twist()
            cmd.linear.y = 0.3
            cmd.angular.z = 0.01
            self.cmd_vel_publisher.publish(cmd) 
            rospy.sleep(0.1)

        #Reset the robot's wheels straight forward
        cmd = Twist()
        cmd.linear.x = 0.02
        self.cmd_vel_publisher.publish(cmd)
        rospy.sleep(0.1)
        self.cmd_vel_publisher.publish(Twist())
        
        self.set_gripper(0.086)
        self.move_to_target(door_center_goal, -math.pi * 6 / 5, True, True)
        self.move_to_target(door_center_goal, -math.pi, True, True)

        #Tuck
        self.tuck_arms()

        self.set_gripper(0.0)

        self.move_to_target(self.generate_goal(1.5, math.pi), 0, True, True)
        self.move_to_target(self.generate_goal(0, 0), math.pi, True, True)

        print "done"
        
        self.drag_server.set_succeeded(GrandSlamTransitionResult())        
        return True

    def set_gripper(self, pos):
        grip = Pr2GripperCommandGoal()
        grip.command.position = pos
        grip.command.max_effort = 10000
        #print grip
        self.gripper.send_goal(grip)
        self.gripper.wait_for_result()

    def tuck_arms(self):
        tuck_goal = TuckArmsGoal()
        tuck_goal.tuck_left = True
        tuck_goal.tuck_right = True
        self.tuck.send_goal(tuck_goal)
        self.tuck.wait_for_result()

        
    def get_end_effector_pos(self):
        self.listener.waitForTransform("/r_wrist_roll_link", "/base_link", rospy.Time(), rospy.Duration(30))
        target, rot = self.listener.lookupTransform("/base_link", "/r_wrist_roll_link", rospy.Time())
        return target


    def arm_move(self, x, y, z, duration=3, wait=True):
        response = self.query_client(GetKinematicSolverInfoRequest())
        if (not response):
            print "Failed - no info:", x, y, z
            return False
        
        kin = GetPositionIKRequest()
        kin.timeout = rospy.Duration(5.0);
        kin.ik_request.ik_link_name = "r_wrist_roll_link"
        kin.ik_request.pose_stamped.header.frame_id = "base_link"
        kin.ik_request.pose_stamped.pose.position.x = x
        kin.ik_request.pose_stamped.pose.position.y = y
        kin.ik_request.pose_stamped.pose.position.z = z
        kin.ik_request.pose_stamped.pose.orientation.x = 0.0
        kin.ik_request.pose_stamped.pose.orientation.y = 0.0
        kin.ik_request.pose_stamped.pose.orientation.z = 0.0
        kin.ik_request.pose_stamped.pose.orientation.w = 1.0
        kin.ik_request.ik_seed_state.joint_state.name = response.kinematic_solver_info.joint_names;
        for i in range(0, len(response.kinematic_solver_info.joint_names)):
            minp = response.kinematic_solver_info.limits[i].min_position 
            maxp = response.kinematic_solver_info.limits[i].max_position
            while (len(kin.ik_request.ik_seed_state.joint_state.position) <= i):
                kin.ik_request.ik_seed_state.joint_state.position += [0.0]
            kin.ik_request.ik_seed_state.joint_state.position[i] = (minp + maxp) / 2.0
        
        resp = self.ik_client(kin)
        if (not resp):
            #FIXME
            print "Failed - no response:", x, y, z
            return False

        if (len(resp.solution.joint_state.position) != len(kin.ik_request.ik_seed_state.joint_state.name)):
            print "Failed - no data:", x, y, z
            return False
        
        goal = JointTrajectory()
        goal.header.stamp = rospy.get_rostime()
        goal.joint_names = kin.ik_request.ik_seed_state.joint_state.name
        goal.points = [JointTrajectoryPoint()]
        goal.points[0].positions = resp.solution.joint_state.position
        goal.points[0].velocities = map(lambda (x): 0.0, resp.solution.joint_state.position)
        goal.points[0].time_from_start = rospy.Duration.from_sec(duration)

        self.arm.publish(goal)
        if (wait):
            rospy.sleep(duration)
        
        return True
        
        

        
    def line_up(self, msg):
        xy = self.scan_to_points(msg)
        xy_c = []
        for i in xy:
            if (i[1] > -0.5 and i[1] < 0.5 and i[0] > 0.2):
                xy_c.append(i)

        marker = Marker()
        marker.header.frame_id = msg.header.frame_id
        marker.header.stamp = rospy.get_rostime()
        marker.ns = "door_blast"
        marker.type = Marker.CUBE
        marker.action = Marker.MODIFY
        marker.id = 0
        marker.pose.position.x = 1.2
        marker.pose.position.y = 0
        marker.pose.position.z = 0.5
        marker.pose.orientation.x = 0.0
        marker.pose.orientation.y = 0.0
        marker.pose.orientation.z = 0.0
        marker.pose.orientation.w = 1.0
        marker.scale.x = 0.5
        marker.scale.y = 1.0
        marker.scale.z = 1
        marker.color.a = 0.1
        marker.color.r = 0.0
        marker.color.g = 0.0
        marker.color.b = 1.0
        self.visualization_publisher.publish(marker)

        #print xy_c
        n = len(xy_c)
        Sx = Sy = Sxx = Syy = Sxy = 0.0
        for pt in xy_c:
            x = pt[1]
            y = pt[0]
            Sx = Sx + x
            Sy = Sy + y
            Sxx = Sxx + x*x
            Syy = Syy + y*y
            Sxy = Sxy + x*y
        det = Sxx * n - Sx * Sx
        a, b = (Sxy * n - Sy * Sx)/det, (Sxx * Sy - Sx * Sxy)/det
        meanerror = residual = 0.0
        for pt in xy_c:
            x = pt[1]
            y = pt[0]
            meanerror = meanerror + (y - Sy/n)**2
            residual = residual + (y - a * x - b)**2
        RR = 1 - residual/meanerror
        ss = residual / (n-2)
        Var_a, Var_b = ss * n / det, ss * Sxx / det
        print a, b, RR
        
        #a = a - 0.12 #FIXME: param for offset

        msg = Twist()
        speed_lim = 0.15 #FIXME param
        scal = 4.0
        if (-a * scal > speed_lim):
            msg.angular.z = speed_lim
        elif (-a * scal < -speed_lim):
            msg.angular.z = -speed_lim
        else:
            msg.angular.z = -a * scal

        print "Line up"
        print msg
        self.cmd_vel_publisher.publish(msg)
        
        tol = 0.005 #FIXME: param

        if (a < tol and a > -tol):
            return a
        return False
        

    def scan_to_points(self, msg):
        xy = []
        angle = msg.angle_min
        for r in range(0, len(msg.ranges)):
            dist = msg.ranges[r]
            xy.append([dist * math.cos(angle), dist * math.sin(angle)])
            angle = angle + msg.angle_increment
        return xy


    def get_vertical_depth(self, msg):
        marker = Marker()
        marker.header.frame_id = msg.header.frame_id
        marker.header.stamp = rospy.get_rostime()
        marker.ns = "door_blast"
        marker.type = Marker.CYLINDER
        marker.action = Marker.MODIFY
        marker.id = 0
        marker.pose.position.x = 0
        marker.pose.position.y = 0
        marker.pose.position.z = 0.5
        marker.pose.orientation.x = 0.0
        marker.pose.orientation.y = 0.0
        marker.pose.orientation.z = 0.0
        marker.pose.orientation.w = 1.0
        marker.scale.x = 0.5
        marker.scale.y = 0.5
        marker.scale.z = 1
        marker.color.a = 1.0
        marker.color.r = 0.0
        marker.color.g = 0.0
        marker.color.b = 1.0
        self.visualization_publisher.publish(marker)
        
        xy = self.scan_to_points(msg)
    
        #Find the distance to the wall
        min_door = False
        for pt in xy:
            if (pt[1] < 0.5 and pt[1] > -0.5 and pt[0] > 0.01):
                if (min_door == False or min_door > pt[0]):
                    min_door = pt[0]
                
        marker = Marker()
        marker.header.frame_id = msg.header.frame_id
        marker.header.stamp = rospy.get_rostime()
        marker.ns = "door_blast"
        marker.type = Marker.CUBE
        marker.action = Marker.MODIFY
        marker.id = 1
        marker.pose.position.x = min_door
        marker.pose.position.y = 0
        marker.pose.position.z = 0.5
        marker.pose.orientation.x = 0.0
        marker.pose.orientation.y = 0.0
        marker.pose.orientation.z = 0.0
        marker.pose.orientation.w = 1.0
        marker.scale.x = 2.0
        marker.scale.y = 2.0
        marker.scale.z = 1
        marker.color.a = 0.4
        marker.color.r = 0.0
        marker.color.g = 0.0
        marker.color.b = 1.0
        self.visualization_publisher.publish(marker)

        goal = PoseStamped()
        goal.header.frame_id = msg.header.frame_id
        dist = min_door
        goal.pose.position.x = min_door
        #print goal
        goal = self.listener.transformPose("/base_link", goal)
        #print goal
        return goal.pose.position.x

    def horizontal_align(self, msg, min_door, offset = -0.1):
        xy = self.scan_to_points(msg)
        
        y_pos = []
        for pt in xy:
            if (pt[1] < 1.0 and pt[1] > -1.0 and \
                    pt[0] > min_door - 0.25 and pt[0] < min_door + 0.25):
                y_pos.append(pt[1])
        y_pos.sort()
        
        if (len(y_pos) == 0):
            return False

        last_pos = y_pos[0]
        max_delta = 0
        best = y_pos[0]
        gaps = []
        
        for i in y_pos:
            delta = i - last_pos
            gaps.append((delta, i + last_pos, i, last_pos))
            last_pos = i

        gaps = sorted(gaps, key=lambda gap: gap[0], reverse=True)
        best = (gaps[0][2] + gaps[0][3]) / 2 + offset
        
        marker = Marker()
        marker.header.frame_id = msg.header.frame_id
        marker.header.stamp = rospy.get_rostime()
        marker.ns = "door_blast"
        marker.type = Marker.CYLINDER
        marker.action = Marker.MODIFY
        marker.id = 2
        marker.pose.position.x = min_door
        marker.pose.position.y = best
        marker.pose.position.z = 0
        marker.pose.orientation.x = 0.0
        marker.pose.orientation.y = 0.0
        marker.pose.orientation.z = 0.0
        marker.pose.orientation.w = 1.0
        marker.scale.x = 0.5
        marker.scale.y = 0.5
        marker.scale.z = 1
        marker.color.a = 1.0
        marker.color.r = 0.0
        marker.color.g = 0.0
        marker.color.b = 1.0
        self.visualization_publisher.publish(marker)

        #print best
        tol = 0.015 #FIXME param
        if (best < tol and best > -tol):
            return True

        msg = Twist()
        speed_lim = 0.1 #FIXME param
        scal = 1.0
        if (best * scal > speed_lim):
            msg.linear.y = speed_lim
        elif (best * scal < -speed_lim):
            msg.linear.y = -speed_lim
        else:
            msg.linear.y = best * scal
        self.cmd_vel_publisher.publish(msg)
        return False

    def delete_markers(self, frame_id, lim):
        for n in range(0, lim):
            marker = Marker()
            marker.header.frame_id = frame_id
            marker.header.stamp = rospy.get_rostime()
            marker.ns = "door_blast"
            marker.type = Marker.CYLINDER
            marker.action = Marker.DELETE
            marker.id = n
            self.visualization_publisher.publish(marker)

    def generate_goal(self, dist, angle, xy = False):
        base_frame = "/base_footprint"
        odom_frame = "/odom_combined" #FIXME param
        
        while not rospy.is_shutdown(): #FIXME
            try:
                self.listener.waitForTransform(base_frame, odom_frame, rospy.Time(), rospy.Duration(30))
                
                goal = PoseStamped()
                goal.header.frame_id = base_frame
                if (xy):
                    goal.pose.position.x = dist
                    goal.pose.position.y = angle
                else:
                    goal.pose.position.x = dist * math.cos(angle)
                    goal.pose.position.y = dist * math.sin(angle)
                goal = self.listener.transformPose(odom_frame, goal)
                #print goal
                break
            except (tf.LookupException, tf.ConnectivityException, tf.ExtrapolationException) as ex:
                rospy.logwarn("TF error") #FIXME: warning
        
        return goal

    def move_to_target(self, goal, angle_offset, no_y_reset=False, extreme_turn=False, time_limit=0):
        base_frame = "/base_footprint"
        odom_frame = "/odom_combined" #FIXME param 
        
        rate = rospy.Rate(10)
        reset = False
        start_time = rospy.get_rostime()
        while not rospy.is_shutdown() and ((rospy.get_rostime() - start_time).to_sec() < time_limit or time_limit == 0): #FIXME
            try:
                goal_transformed = self.listener.transformPose(base_frame, goal)
                
                #print goal_transformed
                
                def scaleclamp(val, scale, lim):
                    t = val * scale
                    if (t > lim):
                        return lim
                    if (t < -lim):
                        return -lim
                    return t
                
                msg = Twist()
                p, r, y = tf.transformations.euler_from_quaternion((goal_transformed.pose.orientation.x,
                                                                    goal_transformed.pose.orientation.y,
                                                                    goal_transformed.pose.orientation.z,
                                                                    goal_transformed.pose.orientation.w))
                msg.angular.x = 0
                msg.angular.y = 0
                if (reset):
                    msg.angular.z = scaleclamp(y, 1, 1.0)
                    while (y > math.pi):
                        y = y - math.pi * 2.0
                    while (y < -math.pi):
                        y = y + math.pi * 2.0
                    if (y > -0.05 and y < 0.05 or no_y_reset):
                        break
                else:
                    w = y + angle_offset
                    print y, angle_offset, w

                    dist = goal_transformed.pose.position.y * goal_transformed.pose.position.y
                    dist = dist + goal_transformed.pose.position.x * goal_transformed.pose.position.x
                    dist = math.sqrt(dist)
                    #print dist

                    #if (dist > 1.6):
                    #    w = w - (math.pi / 8)

                    while (w > math.pi):
                        w = w - math.pi * 2.0
                    while (w < -math.pi):
                        w = w + math.pi * 2.0

                    scale = 1.5
                    if (extreme_turn):
                        scale = 3.0
                    msg.angular.z = scaleclamp(w, scale, 1.0)
                
                    if (w > -0.15 and w < 0.15):
                        if (dist < 0.03): #Fixme
                            if (w > -0.01 and w < 0.01 or not no_y_reset):
                                reset = True

                        dist = scaleclamp(dist, 1.0, 0.4)
                        ang = math.atan2(goal_transformed.pose.position.y, goal_transformed.pose.position.x)
                        msg.linear.x = dist * math.cos(ang)
                        msg.linear.y = dist * math.sin(ang)
                    
                #print "go forward", msg
                
                self.cmd_vel_publisher.publish(msg)
                
                rate.sleep()
            except (tf.LookupException, tf.ConnectivityException, tf.ExtrapolationException) as ex:
                rospy.logwarn("TF error") #FIXME
                

if __name__ == '__main__':
    rospy.init_node("door_blast")
    blast = DoorBlast()
    rospy.spin()
    
