#!/usr/bin/python

import roslib
roslib.load_manifest('multi_map_navigation')
import rospy
import actionlib
import sys
from multi_map_navigation.msg import *
from multi_map_navigation.srv import *


class TestClient():
    def __init__(self, xp, yp, map):
        self.action_client = actionlib.SimpleActionClient("multi_map_navigation/move", MultiMapNavigationAction)
        self.action_client.wait_for_server()
        goal = MultiMapNavigationGoal()
        goal.target_pose.header.stamp = rospy.get_rostime()
        goal.target_pose.header.frame_id = "map"
        goal.target_pose.pose.position.x = xp
        goal.target_pose.pose.position.y = yp
        goal.target_pose.pose.orientation.w = 1.0
        goal.goal_map = map
        self.action_client.send_goal(goal)
        self.action_client.wait_for_result()


if (__name__ == "__main__"):
   rospy.init_node("multi_map_navigation_test")
   xp = float(sys.argv[1])
   yp = float(sys.argv[2])
   map = sys.argv[3] 
   test = TestClient(xp, yp, map)

