#!/usr/bin/python

import roslib
roslib.load_manifest('coffee_grab')
import rospy
import actionlib
import math
import sys, os

from geometry_msgs.msg import *
import tf
from sensor_msgs.msg import *
from robotpass.msg import *
from visualization_msgs.msg import *
from grandslam.msg import *
from pr2_common_action_msgs.msg import *
from geometry_msgs.msg import *
from pr2_controllers_msgs.msg import *
from trajectory_msgs.msg import *

class CoffeeGrab(object):
    def __init__(self):
        self.base_scan_msg = False
        self.listener = tf.TransformListener(True, rospy.Duration(100))
        self.cmd_vel_publisher = rospy.Publisher('/base_controller/command', Twist)
        rospy.loginfo("Wait for object pass")
        self.robotpass = actionlib.SimpleActionClient("pass_object", PassObjectAction)
        self.robotpass.wait_for_server()
        rospy.loginfo("Wait for tuck arm")
        self.tuck = actionlib.SimpleActionClient("tuck_arms", TuckArmsAction)
        self.tuck.wait_for_server()
        rospy.loginfo("Wait for grandslam")
        self.grandslam_ac = actionlib.SimpleActionClient("grandslam/move", GrandSlamAction)
        self.grandslam_ac.wait_for_server()
        rospy.Subscriber("/base_scan", LaserScan, self.on_base_scan)
        self.visualization_publisher = rospy.Publisher("/visualization_markers", Marker)
        rospy.loginfo("Wait for head control")
        self.head_client = actionlib.SimpleActionClient(
            '/head_traj_controller/point_head_action', PointHeadAction)
        self.head_client.wait_for_server()
        rospy.loginfo("Wait for torso")
        self.arm = rospy.Publisher("l_arm_controller/command", JointTrajectory)
        self.torso = actionlib.SimpleActionClient("/torso_controller/position_joint_action", SingleJointPositionAction)
        self.torso.wait_for_server()
        rospy.loginfo("Done starting")

    def set_torso(self, pos, wait):
        traj = SingleJointPositionGoal()
        traj.position = pos
        traj.min_duration = rospy.Duration(1.0)
        traj.max_velocity = 0
        self.torso.send_goal(traj)
        if (wait):
            self.torso.wait_for_result()

    def on_base_scan(self, msg):
        self.base_scan_msg = msg

    def scan_to_points(self, msg):
        xy = []
        angle = msg.angle_min
        for r in range(0, len(msg.ranges)):
            dist = msg.ranges[r]
            xy.append([dist * math.cos(angle), dist * math.sin(angle)])
            angle = angle + msg.angle_increment
        return xy

    def tuck_arms(self, left, right):
        tuck_goal = TuckArmsGoal()
        tuck_goal.tuck_left = left
        tuck_goal.tuck_right = right
        self.tuck.send_goal(tuck_goal)
        self.tuck.wait_for_result()

    def passobject(self, direction, position, obj):
        take_goal = PassObjectGoal()
        take_goal.arm = PassObjectGoal.LEFT_ARM
        take_goal.direction = direction
        take_goal.arm_position = position
        take_goal.object_name = obj
        self.robotpass.send_goal(take_goal)
        self.robotpass.wait_for_result()

    def grandslam(self, x, y, a, name):
        goal = GrandSlamGoal()
        goal.target_pose.header.stamp = rospy.get_rostime()
        goal.target_pose.header.frame_id = "map"
        goal.target_pose.pose.position.x = x
        goal.target_pose.pose.position.y = y
        
        #FIXME
        goal.target_pose.pose.orientation.w = 1.0
        goal.goal_map = name
        self.grandslam_ac.send_goal(goal)
        self.grandslam_ac.wait_for_result()

    def cube(self, f, x, y, z, sx, sy, sz, i):
        marker = Marker()
        marker.header.frame_id = f
        marker.header.stamp = rospy.get_rostime()
        marker.ns = "coffee_grab"
        marker.type = Marker.CUBE
        marker.action = Marker.ADD
        marker.id = i
        marker.pose.position.x = x
        marker.pose.position.y = y
        marker.pose.position.z = z
        marker.pose.orientation.x = 1.0
        marker.pose.orientation.y = 0.0
        marker.pose.orientation.z = 0.0
        marker.pose.orientation.w = 1.0
        marker.scale.x = sx
        marker.scale.y = sy
        marker.scale.z = sz
        marker.color.a = 1.0
        marker.color.r = 0.0
        marker.color.g = 0.0
        marker.color.b = 1.0
        self.visualization_publisher.publish(marker)
        
    def point_head(self, x, y, z, wait=True):
        g = PointHeadGoal()
        g.target.header.frame_id = 'base_link'
        g.target.point.x = x
        g.target.point.y = y
        g.target.point.z = z
        g.min_duration = rospy.Duration(1.0)
        self.head_client.send_goal(g)
        #self.head_client.wait_for_result()
        if (wait):
            rospy.sleep(1.0)

    def thestart(self):
        #Start out with the money bag
        self.tuck_arms(False, True)
        self.passobject(PassObjectGoal.TAKE_OBJECT, PassObjectGoal.HIGH, "empty bag")
        self.tuck_arms(True, True)

        #Go to Ken's office - grandslam
        print "GRANDSLAM: ken's office"
        self.grandslam(17.460, 38.323, -2.330, "clarkcenterfirstfloor")

        print "Grab bag"
        self.tuck_arms(False, True)
        self.passobject(PassObjectGoal.GIVE_OBJECT, PassObjectGoal.HIGH, "empty bag")
        self.passobject(PassObjectGoal.TAKE_OBJECT, PassObjectGoal.HIGH, "money and paper instructions")
        self.tuck_arms(True, True)
    
    def start(self):
        #Go to target - grandslam
        print "GRANDSLAM: coffee shop"
        self.grandslam(56.869, 14.529, 2.511, "clarkcenterpeetscoffee")
        
        #Raise the torso
        print "Rise torso"
        self.set_torso(0.3, True)

        #In the coffee shop - drive a course to wait in line
        print "Coffee course"
        self.move_to_target(58.834, 13.630, -0.697, True)
        self.move_to_target(58.782, 13.704, 2.412, True)
        self.move_to_target(57.840, 14.623, 2.497, True)
        self.move_to_target(57.667, 15.643, 1.731, True)
        self.move_to_target(57.476, 16.429, 1.731, True)
        self.move_to_target(58.521, 17.789, 0.816, True)
        self.move_to_target(58.521, 17.789, -0.687, False)
        
        #Raise the torso
        print "Do course"
        self.set_torso(0.3, True)

        #Get arm
        print "Get arm control"
        self.tuck_arms(False, True)
        self.extend_arm([0.0, -0.350, 0.0, -1.225, 3.14159, -1.65, 0.0])

        #Drive up to the booth
        print "Drive up to the booth"
        for i in range(0, 50):
            t = Twist()
            t.linear.x = 0.1
            self.cmd_vel_publisher.publish(t)
            rospy.sleep(0.1)
        self.cmd_vel_publisher.publish(Twist())

        #Grab the cup
        print "Grab the coffee"
        self.passobject(PassObjectGoal.GIVE_OBJECT, PassObjectGoal.HIGH, "money and paper instructions")
        self.passobject(PassObjectGoal.TAKE_OBJECT, PassObjectGoal.HIGH, "cup")

        #Scary, but there are no other alternatives 
        print "Back up"
        for i in range(0, 20):
            t = Twist()
            t.linear.x = -0.3
            self.cmd_vel_publisher.publish(t)
            rospy.sleep(0.1)
        self.cmd_vel_publisher.publish(Twist())

        self.passobject(PassObjectGoal.STASH_OBJECT, PassObjectGoal.HIGH, "cup")

        self.tuck_arms(True, True)

        #Return to ken's office
        print "GRANDSLAM: ken's office"
        #self.grandslam(17.460, 38.323, -2.330, "clarkcenterfirstfloor") #Actual office location
        #self.grandslam(56.869, 14.529, 2.511, "clarkcenterpeetscoffee") #Test in Peets for debuging
        self.grandslam(95.647, 62.677, 0, "clarkcenterfirstflooroutside") #Test location at the base of th elevator

        #Untuck
        print "Done"
        self.tuck_arms(False, True)
        self.passobject(PassObjectGoal.UNSTASH_OBJECT, PassObjectGoal.HIGH, "cup")
        self.passobject(PassObjectGoal.GIVE_OBJECT, PassObjectGoal.HIGH, "cup")
        self.tuck_arms(True, True)

        print "GRANDSLAM: base"

    def extend_arm(self, force):
        goal = JointTrajectory()
        goal.header.stamp = rospy.get_rostime()
        goal.joint_names = ["l_shoulder_pan_joint", "l_shoulder_lift_joint",
                            "l_upper_arm_roll_joint",
                            "l_elbow_flex_joint", "l_forearm_roll_joint",
                            "l_wrist_flex_joint", "l_wrist_roll_joint"]
        goal.points = [JointTrajectoryPoint()]
        goal.points[0].positions = force
        goal.points[0].velocities = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        goal.points[0].time_from_start = rospy.Duration.from_sec(3.0)
        self.arm.publish(goal)
        rospy.sleep(3.0)

    def move_to_target(self, g_x, g_y, g_a, watch_scans=False):
        base_frame = "/base_footprint" #FIXME: param
        map_frame = "/map"
        
        while not rospy.is_shutdown():
            try:
                self.listener.waitForTransform(base_frame, map_frame,
                                               rospy.Time(), rospy.Duration(30))
                
                goal = PoseStamped()
                goal.header.frame_id = map_frame
                goal.pose.position.x = g_x
                goal.pose.position.y = g_y
                quat = tf.transformations.quaternion_from_euler(0, 0, g_a)
                goal.pose.orientation.x = quat[0]
                goal.pose.orientation.y = quat[1]
                goal.pose.orientation.z = quat[2]
                goal.pose.orientation.w = quat[3]
                goal = self.listener.transformPose(map_frame, goal)
                print goal
                break
            except (tf.LookupException, tf.ConnectivityException,
                    tf.ExtrapolationException) as ex:
                rospy.logwarn("TF error") #FIXME: warning
        

        rate = rospy.Rate(10)
        while not rospy.is_shutdown():
            try:
                goal_transformed = self.listener.transformPose(base_frame, goal)
                
                #print goal_transformed
                
                def scaleclamp(val, scale, lim, min_v = 0):
                    t = val * scale
                    if (t > lim):
                        return lim
                    if (t < -lim):
                        return -lim
                    if (t < min_v and t > -min_v):
                        if (t < 0):
                            t = -min_v
                        if (t > 0):
                            t = min_v
                    return t
                
                msg = Twist()
                p, r, y = tf.transformations.euler_from_quaternion(
                    (goal_transformed.pose.orientation.x,
                     goal_transformed.pose.orientation.y,
                     goal_transformed.pose.orientation.z,
                     goal_transformed.pose.orientation.w))
                msg.angular.x = 0
                msg.angular.y = 0
                msg.linear.x = 0
                msg.linear.y = 0
                if (y < -0.01 or y > 0.01):
                    msg.angular.z = scaleclamp(y, 3, 0.5, 0.005)
                if (y > -0.1 and y < 0.1):
                    dist = goal_transformed.pose.position.y \
                        * goal_transformed.pose.position.y
                    dist = dist + goal_transformed.pose.position.x \
                        * goal_transformed.pose.position.x
                    dist = math.sqrt(dist)

                
                    if (dist < 0.03 and msg.angular.z == 0.0):
                        break

                    ang = math.atan2(goal_transformed.pose.position.y,
                                     goal_transformed.pose.position.x)
                    x_dist = dist * math.cos(ang)
                    y_dist = dist * math.sin(ang)
                    dist = scaleclamp(dist, 1.0, 0.3)
                    msg.linear.x = dist * math.cos(ang)
                    msg.linear.y = dist * math.sin(ang)
                    
                    if (watch_scans != False):
                        while not rospy.is_shutdown() and not self.base_scan_msg:
                            rospy.sleep(0.001)
                        if (self.base_scan_msg == False):
                            return False
                        pts = self.scan_to_points(self.base_scan_msg)
                        blocked = False
                        if (msg.linear.x > 0.1 and len(pts) > 0):
                            right_wall = False
                            left_wall = False
                            for i in pts:
                                if (i[1] > 0.0):
                                    if (not right_wall):
                                        right_wall = i
                                    elif (abs(right_wall[0]) > abs(i[0])):
                                        right_wall = i
                                if (i[1] < 0.0):
                                    if (not left_wall):
                                        left_wall = i
                                    elif (abs(left_wall[0]) > abs(i[0])):
                                        left_wall = i

                            if (left_wall):
                                self.cube(self.base_scan_msg.header.frame_id, 
                                          left_wall[0], left_wall[1], 0, 0.2, 0.2, 0.2, 0)
                            if (right_wall):
                                self.cube(self.base_scan_msg.header.frame_id,
                                          right_wall[0], right_wall[1], 0, 0.2, 0.2, 0.2, 1)


                            wall_max_width = 0.4
                            if (left_wall):
                                if (abs(left_wall[1]) < wall_max_width):
                                    left_wall = abs(left_wall[1]) - 0.1
                                else:
                                    left_wall = wall_max_width
                            else:
                                left_wall = wall_max_width
                            if (right_wall):
                                if (abs(right_wall[1]) < wall_max_width):
                                    right_wall = abs(right_wall[1]) - 0.1
                                else:
                                    right_wall = wall_max_width
                            else:
                                right_wall = wall_max_width
                            #print right_wall, left_wall

                            x_lim = 0.5
                            offset_x = -0.2
                            if (x_dist - offset_x < x_lim):
                                x_lim = x_dist - offset_x


                            self.cube(self.base_scan_msg.header.frame_id, x_lim / 2.0, 
                                      right_wall - (right_wall + left_wall) / 2.0, 0,
                                      x_lim, 0.2, right_wall + left_wall, 2)

                            for i in pts:
                                if (i[0] < x_lim and i[0] > 0.00 \
                                        and i[1] < right_wall and i[1] > -left_wall):
                                    blocked = True

                        if (blocked):
                            msg.linear.x = 0
                            msg.linear.y = 0
                            self.point_head(1.0, 0, 0.0, False)
                        else:
                            self.point_head(1.0, 0, 2.0, False)
                    else:
                        self.point_head(1.0, 0, 2.0, False)
                else:
                    self.point_head(1.0, 0, 2.0, False)

                self.cmd_vel_publisher.publish(msg)
                
                rate.sleep()
            except (tf.LookupException, tf.ConnectivityException,
                    tf.ExtrapolationException) as ex:
                rospy.logwarn("TF error") #FIXME
        return True
        

##################
if __name__ == '__main__':
    rospy.init_node('coffee_grabber')
    server = CoffeeGrab()
    server.start()
    #rospy.spin()








