# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logger.ui'
#
# Created: Fri Jun 17 01:11:41 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2.addLayout(self.gridLayout, 2, 4, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.start_pause = QtGui.QPushButton(self.centralwidget)
        self.start_pause.setObjectName("start_pause")
        self.gridLayout_3.addWidget(self.start_pause, 3, 0, 1, 1)
        self.m1 = QtGui.QCheckBox(self.centralwidget)
        self.m1.setObjectName("m1")
        self.gridLayout_3.addWidget(self.m1, 4, 0, 1, 1)
        self.m2 = QtGui.QCheckBox(self.centralwidget)
        self.m2.setObjectName("m2")
        self.gridLayout_3.addWidget(self.m2, 5, 0, 1, 1)
        self.accX1 = QtGui.QCheckBox(self.centralwidget)
        self.accX1.setObjectName("accX1")
        self.gridLayout_3.addWidget(self.accX1, 8, 0, 1, 1)
        self.accY1 = QtGui.QCheckBox(self.centralwidget)
        self.accY1.setObjectName("accY1")
        self.gridLayout_3.addWidget(self.accY1, 9, 0, 1, 1)
        self.m3 = QtGui.QCheckBox(self.centralwidget)
        self.m3.setObjectName("m3")
        self.gridLayout_3.addWidget(self.m3, 6, 0, 1, 1)
        self.accZ1 = QtGui.QCheckBox(self.centralwidget)
        self.accZ1.setObjectName("accZ1")
        self.gridLayout_3.addWidget(self.accZ1, 10, 0, 1, 1)
        self.m4 = QtGui.QCheckBox(self.centralwidget)
        self.m4.setObjectName("m4")
        self.gridLayout_3.addWidget(self.m4, 7, 0, 1, 1)
        self.accX2 = QtGui.QCheckBox(self.centralwidget)
        self.accX2.setObjectName("accX2")
        self.gridLayout_3.addWidget(self.accX2, 11, 0, 1, 1)
        self.t1 = QtGui.QCheckBox(self.centralwidget)
        self.t1.setObjectName("t1")
        self.gridLayout_3.addWidget(self.t1, 14, 0, 1, 1)
        self.t2 = QtGui.QCheckBox(self.centralwidget)
        self.t2.setObjectName("t2")
        self.gridLayout_3.addWidget(self.t2, 15, 0, 1, 1)
        self.t3 = QtGui.QCheckBox(self.centralwidget)
        self.t3.setObjectName("t3")
        self.gridLayout_3.addWidget(self.t3, 16, 0, 1, 1)
        self.t4 = QtGui.QCheckBox(self.centralwidget)
        self.t4.setObjectName("t4")
        self.gridLayout_3.addWidget(self.t4, 17, 0, 1, 1)
        self.accY2 = QtGui.QCheckBox(self.centralwidget)
        self.accY2.setObjectName("accY2")
        self.gridLayout_3.addWidget(self.accY2, 12, 0, 1, 1)
        self.accZ2 = QtGui.QCheckBox(self.centralwidget)
        self.accZ2.setObjectName("accZ2")
        self.gridLayout_3.addWidget(self.accZ2, 13, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_force_profile = QtGui.QAction(MainWindow)
        self.actionOpen_force_profile.setObjectName("actionOpen_force_profile")
        self.menuFile.addAction(self.actionOpen_force_profile)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.start_pause.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.m1.setText(QtGui.QApplication.translate("MainWindow", "m1", None, QtGui.QApplication.UnicodeUTF8))
        self.m2.setText(QtGui.QApplication.translate("MainWindow", "m2", None, QtGui.QApplication.UnicodeUTF8))
        self.accX1.setText(QtGui.QApplication.translate("MainWindow", "accX1", None, QtGui.QApplication.UnicodeUTF8))
        self.accY1.setText(QtGui.QApplication.translate("MainWindow", "accY1", None, QtGui.QApplication.UnicodeUTF8))
        self.m3.setText(QtGui.QApplication.translate("MainWindow", "m3", None, QtGui.QApplication.UnicodeUTF8))
        self.accZ1.setText(QtGui.QApplication.translate("MainWindow", "accZ1", None, QtGui.QApplication.UnicodeUTF8))
        self.m4.setText(QtGui.QApplication.translate("MainWindow", "m4", None, QtGui.QApplication.UnicodeUTF8))
        self.accX2.setText(QtGui.QApplication.translate("MainWindow", "accX2", None, QtGui.QApplication.UnicodeUTF8))
        self.t1.setText(QtGui.QApplication.translate("MainWindow", "t1", None, QtGui.QApplication.UnicodeUTF8))
        self.t2.setText(QtGui.QApplication.translate("MainWindow", "t2", None, QtGui.QApplication.UnicodeUTF8))
        self.t3.setText(QtGui.QApplication.translate("MainWindow", "t3", None, QtGui.QApplication.UnicodeUTF8))
        self.t4.setText(QtGui.QApplication.translate("MainWindow", "t4", None, QtGui.QApplication.UnicodeUTF8))
        self.accY2.setText(QtGui.QApplication.translate("MainWindow", "accY2", None, QtGui.QApplication.UnicodeUTF8))
        self.accZ2.setText(QtGui.QApplication.translate("MainWindow", "accZ2", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_force_profile.setText(QtGui.QApplication.translate("MainWindow", "Open force profile", None, QtGui.QApplication.UnicodeUTF8))

