# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logger.ui'
#
# Created: Sat Jul  2 22:15:19 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 708)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2.addLayout(self.gridLayout, 1, 3, 2, 1)
        self.gridLayout2 = QtGui.QGridLayout()
        self.gridLayout2.setObjectName("gridLayout2")
        self.m1 = QtGui.QCheckBox(self.centralwidget)
        self.m1.setObjectName("m1")
        self.gridLayout2.addWidget(self.m1, 0, 0, 1, 1)
        self.tm1 = QtGui.QCheckBox(self.centralwidget)
        self.tm1.setObjectName("tm1")
        self.gridLayout2.addWidget(self.tm1, 0, 2, 1, 1)
        self.m2 = QtGui.QCheckBox(self.centralwidget)
        self.m2.setObjectName("m2")
        self.gridLayout2.addWidget(self.m2, 1, 0, 1, 1)
        self.m3 = QtGui.QCheckBox(self.centralwidget)
        self.m3.setObjectName("m3")
        self.gridLayout2.addWidget(self.m3, 2, 0, 1, 1)
        self.m4 = QtGui.QCheckBox(self.centralwidget)
        self.m4.setObjectName("m4")
        self.gridLayout2.addWidget(self.m4, 3, 0, 1, 1)
        self.tm2 = QtGui.QCheckBox(self.centralwidget)
        self.tm2.setObjectName("tm2")
        self.gridLayout2.addWidget(self.tm2, 1, 2, 1, 1)
        self.tm3 = QtGui.QCheckBox(self.centralwidget)
        self.tm3.setObjectName("tm3")
        self.gridLayout2.addWidget(self.tm3, 2, 2, 1, 1)
        self.tm4 = QtGui.QCheckBox(self.centralwidget)
        self.tm4.setObjectName("tm4")
        self.gridLayout2.addWidget(self.tm4, 3, 2, 1, 1)
        self.q1 = QtGui.QCheckBox(self.centralwidget)
        self.q1.setObjectName("q1")
        self.gridLayout2.addWidget(self.q1, 4, 0, 1, 1)
        self.q2 = QtGui.QCheckBox(self.centralwidget)
        self.q2.setObjectName("q2")
        self.gridLayout2.addWidget(self.q2, 5, 0, 1, 1)
        self.q3 = QtGui.QCheckBox(self.centralwidget)
        self.q3.setObjectName("q3")
        self.gridLayout2.addWidget(self.q3, 6, 0, 1, 1)
        self.q4 = QtGui.QCheckBox(self.centralwidget)
        self.q4.setObjectName("q4")
        self.gridLayout2.addWidget(self.q4, 7, 0, 1, 1)
        self.tq1 = QtGui.QCheckBox(self.centralwidget)
        self.tq1.setObjectName("tq1")
        self.gridLayout2.addWidget(self.tq1, 4, 2, 1, 1)
        self.tq2 = QtGui.QCheckBox(self.centralwidget)
        self.tq2.setObjectName("tq2")
        self.gridLayout2.addWidget(self.tq2, 5, 2, 1, 1)
        self.tq3 = QtGui.QCheckBox(self.centralwidget)
        self.tq3.setObjectName("tq3")
        self.gridLayout2.addWidget(self.tq3, 6, 2, 1, 1)
        self.tq4 = QtGui.QCheckBox(self.centralwidget)
        self.tq4.setObjectName("tq4")
        self.gridLayout2.addWidget(self.tq4, 7, 2, 1, 1)
        self.x1 = QtGui.QCheckBox(self.centralwidget)
        self.x1.setObjectName("x1")
        self.gridLayout2.addWidget(self.x1, 8, 0, 1, 1)
        self.x2 = QtGui.QCheckBox(self.centralwidget)
        self.x2.setObjectName("x2")
        self.gridLayout2.addWidget(self.x2, 9, 0, 1, 1)
        self.x3 = QtGui.QCheckBox(self.centralwidget)
        self.x3.setObjectName("x3")
        self.gridLayout2.addWidget(self.x3, 10, 0, 1, 1)
        self.tx1 = QtGui.QCheckBox(self.centralwidget)
        self.tx1.setObjectName("tx1")
        self.gridLayout2.addWidget(self.tx1, 8, 2, 1, 1)
        self.tx2 = QtGui.QCheckBox(self.centralwidget)
        self.tx2.setObjectName("tx2")
        self.gridLayout2.addWidget(self.tx2, 9, 2, 1, 1)
        self.tx3 = QtGui.QCheckBox(self.centralwidget)
        self.tx3.setObjectName("tx3")
        self.gridLayout2.addWidget(self.tx3, 10, 2, 1, 1)
        self.accX1 = QtGui.QCheckBox(self.centralwidget)
        self.accX1.setObjectName("accX1")
        self.gridLayout2.addWidget(self.accX1, 0, 3, 1, 1)
        self.accY1 = QtGui.QCheckBox(self.centralwidget)
        self.accY1.setObjectName("accY1")
        self.gridLayout2.addWidget(self.accY1, 1, 3, 1, 1)
        self.accZ1 = QtGui.QCheckBox(self.centralwidget)
        self.accZ1.setObjectName("accZ1")
        self.gridLayout2.addWidget(self.accZ1, 2, 3, 1, 1)
        self.accX2 = QtGui.QCheckBox(self.centralwidget)
        self.accX2.setObjectName("accX2")
        self.gridLayout2.addWidget(self.accX2, 3, 3, 1, 1)
        self.accY2 = QtGui.QCheckBox(self.centralwidget)
        self.accY2.setObjectName("accY2")
        self.gridLayout2.addWidget(self.accY2, 4, 3, 1, 1)
        self.accZ2 = QtGui.QCheckBox(self.centralwidget)
        self.accZ2.setObjectName("accZ2")
        self.gridLayout2.addWidget(self.accZ2, 5, 3, 1, 1)
        self.vm1 = QtGui.QCheckBox(self.centralwidget)
        self.vm1.setObjectName("vm1")
        self.gridLayout2.addWidget(self.vm1, 0, 1, 1, 1)
        self.vm2 = QtGui.QCheckBox(self.centralwidget)
        self.vm2.setObjectName("vm2")
        self.gridLayout2.addWidget(self.vm2, 1, 1, 1, 1)
        self.vm3 = QtGui.QCheckBox(self.centralwidget)
        self.vm3.setObjectName("vm3")
        self.gridLayout2.addWidget(self.vm3, 2, 1, 1, 1)
        self.vm4 = QtGui.QCheckBox(self.centralwidget)
        self.vm4.setObjectName("vm4")
        self.gridLayout2.addWidget(self.vm4, 3, 1, 1, 1)
        self.vq1 = QtGui.QCheckBox(self.centralwidget)
        self.vq1.setObjectName("vq1")
        self.gridLayout2.addWidget(self.vq1, 4, 1, 1, 1)
        self.vq2 = QtGui.QCheckBox(self.centralwidget)
        self.vq2.setObjectName("vq2")
        self.gridLayout2.addWidget(self.vq2, 5, 1, 1, 1)
        self.vq3 = QtGui.QCheckBox(self.centralwidget)
        self.vq3.setObjectName("vq3")
        self.gridLayout2.addWidget(self.vq3, 6, 1, 1, 1)
        self.vq4 = QtGui.QCheckBox(self.centralwidget)
        self.vq4.setObjectName("vq4")
        self.gridLayout2.addWidget(self.vq4, 7, 1, 1, 1)
        self.vx1 = QtGui.QCheckBox(self.centralwidget)
        self.vx1.setObjectName("vx1")
        self.gridLayout2.addWidget(self.vx1, 8, 1, 1, 1)
        self.vx2 = QtGui.QCheckBox(self.centralwidget)
        self.vx2.setObjectName("vx2")
        self.gridLayout2.addWidget(self.vx2, 9, 1, 1, 1)
        self.vx3 = QtGui.QCheckBox(self.centralwidget)
        self.vx3.setObjectName("vx3")
        self.gridLayout2.addWidget(self.vx3, 10, 1, 1, 1)
        self.em1 = QtGui.QCheckBox(self.centralwidget)
        self.em1.setObjectName("em1")
        self.gridLayout2.addWidget(self.em1, 14, 0, 1, 1)
        self.em2 = QtGui.QCheckBox(self.centralwidget)
        self.em2.setObjectName("em2")
        self.gridLayout2.addWidget(self.em2, 14, 1, 1, 1)
        self.em3 = QtGui.QCheckBox(self.centralwidget)
        self.em3.setObjectName("em3")
        self.gridLayout2.addWidget(self.em3, 14, 2, 1, 1)
        self.em4 = QtGui.QCheckBox(self.centralwidget)
        self.em4.setObjectName("em4")
        self.gridLayout2.addWidget(self.em4, 14, 3, 1, 1)
        self.eq1 = QtGui.QCheckBox(self.centralwidget)
        self.eq1.setObjectName("eq1")
        self.gridLayout2.addWidget(self.eq1, 15, 0, 1, 1)
        self.eq2 = QtGui.QCheckBox(self.centralwidget)
        self.eq2.setObjectName("eq2")
        self.gridLayout2.addWidget(self.eq2, 15, 1, 1, 1)
        self.eq3 = QtGui.QCheckBox(self.centralwidget)
        self.eq3.setObjectName("eq3")
        self.gridLayout2.addWidget(self.eq3, 15, 2, 1, 1)
        self.eq4 = QtGui.QCheckBox(self.centralwidget)
        self.eq4.setObjectName("eq4")
        self.gridLayout2.addWidget(self.eq4, 15, 3, 1, 1)
        self.ex1 = QtGui.QCheckBox(self.centralwidget)
        self.ex1.setObjectName("ex1")
        self.gridLayout2.addWidget(self.ex1, 16, 0, 1, 1)
        self.ex2 = QtGui.QCheckBox(self.centralwidget)
        self.ex2.setObjectName("ex2")
        self.gridLayout2.addWidget(self.ex2, 16, 1, 1, 1)
        self.ex3 = QtGui.QCheckBox(self.centralwidget)
        self.ex3.setObjectName("ex3")
        self.gridLayout2.addWidget(self.ex3, 16, 2, 1, 1)
        self.start_pause = QtGui.QPushButton(self.centralwidget)
        self.start_pause.setObjectName("start_pause")
        self.gridLayout2.addWidget(self.start_pause, 16, 3, 1, 1)
        self.cm1 = QtGui.QCheckBox(self.centralwidget)
        self.cm1.setObjectName("cm1")
        self.gridLayout2.addWidget(self.cm1, 11, 0, 1, 1)
        self.cm2 = QtGui.QCheckBox(self.centralwidget)
        self.cm2.setObjectName("cm2")
        self.gridLayout2.addWidget(self.cm2, 11, 1, 1, 1)
        self.cm3 = QtGui.QCheckBox(self.centralwidget)
        self.cm3.setObjectName("cm3")
        self.gridLayout2.addWidget(self.cm3, 11, 2, 1, 1)
        self.cm4 = QtGui.QCheckBox(self.centralwidget)
        self.cm4.setObjectName("cm4")
        self.gridLayout2.addWidget(self.cm4, 11, 3, 1, 1)
        self.cq1 = QtGui.QCheckBox(self.centralwidget)
        self.cq1.setObjectName("cq1")
        self.gridLayout2.addWidget(self.cq1, 12, 0, 1, 1)
        self.cq2 = QtGui.QCheckBox(self.centralwidget)
        self.cq2.setObjectName("cq2")
        self.gridLayout2.addWidget(self.cq2, 12, 1, 1, 1)
        self.cq3 = QtGui.QCheckBox(self.centralwidget)
        self.cq3.setObjectName("cq3")
        self.gridLayout2.addWidget(self.cq3, 12, 2, 1, 1)
        self.cq4 = QtGui.QCheckBox(self.centralwidget)
        self.cq4.setObjectName("cq4")
        self.gridLayout2.addWidget(self.cq4, 12, 3, 1, 1)
        self.cx1 = QtGui.QCheckBox(self.centralwidget)
        self.cx1.setObjectName("cx1")
        self.gridLayout2.addWidget(self.cx1, 13, 0, 1, 1)
        self.cx2 = QtGui.QCheckBox(self.centralwidget)
        self.cx2.setObjectName("cx2")
        self.gridLayout2.addWidget(self.cx2, 13, 1, 1, 1)
        self.cx3 = QtGui.QCheckBox(self.centralwidget)
        self.cx3.setObjectName("cx3")
        self.gridLayout2.addWidget(self.cx3, 13, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout2, 1, 2, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_force_profile = QtGui.QAction(MainWindow)
        self.actionOpen_force_profile.setObjectName("actionOpen_force_profile")
        self.menuFile.addAction(self.actionOpen_force_profile)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.m1.setText(QtGui.QApplication.translate("MainWindow", "m1", None, QtGui.QApplication.UnicodeUTF8))
        self.tm1.setText(QtGui.QApplication.translate("MainWindow", "tm1", None, QtGui.QApplication.UnicodeUTF8))
        self.m2.setText(QtGui.QApplication.translate("MainWindow", "m2", None, QtGui.QApplication.UnicodeUTF8))
        self.m3.setText(QtGui.QApplication.translate("MainWindow", "m3", None, QtGui.QApplication.UnicodeUTF8))
        self.m4.setText(QtGui.QApplication.translate("MainWindow", "m4", None, QtGui.QApplication.UnicodeUTF8))
        self.tm2.setText(QtGui.QApplication.translate("MainWindow", "tm2", None, QtGui.QApplication.UnicodeUTF8))
        self.tm3.setText(QtGui.QApplication.translate("MainWindow", "tm3", None, QtGui.QApplication.UnicodeUTF8))
        self.tm4.setText(QtGui.QApplication.translate("MainWindow", "tm4", None, QtGui.QApplication.UnicodeUTF8))
        self.q1.setText(QtGui.QApplication.translate("MainWindow", "q1", None, QtGui.QApplication.UnicodeUTF8))
        self.q2.setText(QtGui.QApplication.translate("MainWindow", "q2", None, QtGui.QApplication.UnicodeUTF8))
        self.q3.setText(QtGui.QApplication.translate("MainWindow", "q3", None, QtGui.QApplication.UnicodeUTF8))
        self.q4.setText(QtGui.QApplication.translate("MainWindow", "q4", None, QtGui.QApplication.UnicodeUTF8))
        self.tq1.setText(QtGui.QApplication.translate("MainWindow", "tq1", None, QtGui.QApplication.UnicodeUTF8))
        self.tq2.setText(QtGui.QApplication.translate("MainWindow", "tq2", None, QtGui.QApplication.UnicodeUTF8))
        self.tq3.setText(QtGui.QApplication.translate("MainWindow", "tq3", None, QtGui.QApplication.UnicodeUTF8))
        self.tq4.setText(QtGui.QApplication.translate("MainWindow", "tq4", None, QtGui.QApplication.UnicodeUTF8))
        self.x1.setText(QtGui.QApplication.translate("MainWindow", "x1", None, QtGui.QApplication.UnicodeUTF8))
        self.x2.setText(QtGui.QApplication.translate("MainWindow", "x2", None, QtGui.QApplication.UnicodeUTF8))
        self.x3.setText(QtGui.QApplication.translate("MainWindow", "x3", None, QtGui.QApplication.UnicodeUTF8))
        self.tx1.setText(QtGui.QApplication.translate("MainWindow", "tx1", None, QtGui.QApplication.UnicodeUTF8))
        self.tx2.setText(QtGui.QApplication.translate("MainWindow", "tx2", None, QtGui.QApplication.UnicodeUTF8))
        self.tx3.setText(QtGui.QApplication.translate("MainWindow", "tx3", None, QtGui.QApplication.UnicodeUTF8))
        self.accX1.setText(QtGui.QApplication.translate("MainWindow", "accX1", None, QtGui.QApplication.UnicodeUTF8))
        self.accY1.setText(QtGui.QApplication.translate("MainWindow", "accY1", None, QtGui.QApplication.UnicodeUTF8))
        self.accZ1.setText(QtGui.QApplication.translate("MainWindow", "accZ1", None, QtGui.QApplication.UnicodeUTF8))
        self.accX2.setText(QtGui.QApplication.translate("MainWindow", "accX2", None, QtGui.QApplication.UnicodeUTF8))
        self.accY2.setText(QtGui.QApplication.translate("MainWindow", "accY2", None, QtGui.QApplication.UnicodeUTF8))
        self.accZ2.setText(QtGui.QApplication.translate("MainWindow", "accZ2", None, QtGui.QApplication.UnicodeUTF8))
        self.vm1.setText(QtGui.QApplication.translate("MainWindow", "vm1", None, QtGui.QApplication.UnicodeUTF8))
        self.vm2.setText(QtGui.QApplication.translate("MainWindow", "vm2", None, QtGui.QApplication.UnicodeUTF8))
        self.vm3.setText(QtGui.QApplication.translate("MainWindow", "vm3", None, QtGui.QApplication.UnicodeUTF8))
        self.vm4.setText(QtGui.QApplication.translate("MainWindow", "vm4", None, QtGui.QApplication.UnicodeUTF8))
        self.vq1.setText(QtGui.QApplication.translate("MainWindow", "vq1", None, QtGui.QApplication.UnicodeUTF8))
        self.vq2.setText(QtGui.QApplication.translate("MainWindow", "vq2", None, QtGui.QApplication.UnicodeUTF8))
        self.vq3.setText(QtGui.QApplication.translate("MainWindow", "vq3", None, QtGui.QApplication.UnicodeUTF8))
        self.vq4.setText(QtGui.QApplication.translate("MainWindow", "vq4", None, QtGui.QApplication.UnicodeUTF8))
        self.vx1.setText(QtGui.QApplication.translate("MainWindow", "vx1", None, QtGui.QApplication.UnicodeUTF8))
        self.vx2.setText(QtGui.QApplication.translate("MainWindow", "vx2", None, QtGui.QApplication.UnicodeUTF8))
        self.vx3.setText(QtGui.QApplication.translate("MainWindow", "vx3", None, QtGui.QApplication.UnicodeUTF8))
        self.em1.setText(QtGui.QApplication.translate("MainWindow", "em1", None, QtGui.QApplication.UnicodeUTF8))
        self.em2.setText(QtGui.QApplication.translate("MainWindow", "em2", None, QtGui.QApplication.UnicodeUTF8))
        self.em3.setText(QtGui.QApplication.translate("MainWindow", "em3", None, QtGui.QApplication.UnicodeUTF8))
        self.em4.setText(QtGui.QApplication.translate("MainWindow", "em4", None, QtGui.QApplication.UnicodeUTF8))
        self.eq1.setText(QtGui.QApplication.translate("MainWindow", "eq1", None, QtGui.QApplication.UnicodeUTF8))
        self.eq2.setText(QtGui.QApplication.translate("MainWindow", "eq2", None, QtGui.QApplication.UnicodeUTF8))
        self.eq3.setText(QtGui.QApplication.translate("MainWindow", "eq3", None, QtGui.QApplication.UnicodeUTF8))
        self.eq4.setText(QtGui.QApplication.translate("MainWindow", "eq4", None, QtGui.QApplication.UnicodeUTF8))
        self.ex1.setText(QtGui.QApplication.translate("MainWindow", "ex1", None, QtGui.QApplication.UnicodeUTF8))
        self.ex2.setText(QtGui.QApplication.translate("MainWindow", "ex2", None, QtGui.QApplication.UnicodeUTF8))
        self.ex3.setText(QtGui.QApplication.translate("MainWindow", "ex3", None, QtGui.QApplication.UnicodeUTF8))
        self.start_pause.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.cm1.setText(QtGui.QApplication.translate("MainWindow", "cm1", None, QtGui.QApplication.UnicodeUTF8))
        self.cm2.setText(QtGui.QApplication.translate("MainWindow", "cm2", None, QtGui.QApplication.UnicodeUTF8))
        self.cm3.setText(QtGui.QApplication.translate("MainWindow", "cm3", None, QtGui.QApplication.UnicodeUTF8))
        self.cm4.setText(QtGui.QApplication.translate("MainWindow", "cm4", None, QtGui.QApplication.UnicodeUTF8))
        self.cq1.setText(QtGui.QApplication.translate("MainWindow", "cq1", None, QtGui.QApplication.UnicodeUTF8))
        self.cq2.setText(QtGui.QApplication.translate("MainWindow", "cq2", None, QtGui.QApplication.UnicodeUTF8))
        self.cq3.setText(QtGui.QApplication.translate("MainWindow", "cq3", None, QtGui.QApplication.UnicodeUTF8))
        self.cq4.setText(QtGui.QApplication.translate("MainWindow", "cq4", None, QtGui.QApplication.UnicodeUTF8))
        self.cx1.setText(QtGui.QApplication.translate("MainWindow", "cx1", None, QtGui.QApplication.UnicodeUTF8))
        self.cx2.setText(QtGui.QApplication.translate("MainWindow", "cx2", None, QtGui.QApplication.UnicodeUTF8))
        self.cx3.setText(QtGui.QApplication.translate("MainWindow", "cx3", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_force_profile.setText(QtGui.QApplication.translate("MainWindow", "Open force profile", None, QtGui.QApplication.UnicodeUTF8))

