#!/usr/bin/python

import roslib
roslib.load_manifest('grandslam')
import rospy
import actionlib
from grandslam.msg import *

server = None

def vacuous(data):
    global server
    server.set_succeeded(GrandSlamTransitionResult())

if (__name__ == '__main__'):
   client = sys.argv[1]
   rospy.init_node(client)
   server = actionlib.SimpleActionServer(client, GrandSlamTransitionAction, execute_cb = vacuous, auto_start = False)
   server.start()
   rospy.spin()
