#  Copyright (C) 2003-2011 by CHAI 3D.
#  All Rights Reserved.
#
#  $Author: seb $
#  $Date: 2011-12-14 02:23:08 -0800 (Wed, 14 Dec 2011) $
#  $Rev: 667 $


# edit configuration variables for each external library:
# 'no'  builds CHAi3D with built-in support for that particular library
# 'yes' builds CHAi3D against your local system versions of the library

USE_EXTERNAL_LIBPNG  ?= no
USE_EXTERNAL_LIBJPEG ?= no
USE_EXTERNAL_GIFLIB  ?= no
