#!/usr/bin/python

import roslib
roslib.load_manifest('grandslam')
import rospy
import actionlib
import sys
from grandslam.msg import *
from grandslam.srv import *


class TestClient():
    def __init__(self, name):
        self.action_client = actionlib.SimpleActionClient(name, GrandSlamTransitionAction)
        self.action_client.wait_for_server()
        goal = GrandSlamTransitionGoal()
        self.action_client.send_goal(goal)
        self.action_client.wait_for_result()


if (__name__ == "__main__"):
   rospy.init_node("grandslam_test")
   name = sys.argv[1]
   test = TestClient(name)

